Repository mittwald/harbor-operator, pull requests merged in 2020-05, with the labels that each got.

#3 refactor fetching parent harbor instances
  README.md
  pkg/controller/instance/instance_controller.go
  pkg/controller/internal/harbor_commons.go
  pkg/controller/registry/registry_controller.go
  pkg/controller/replication/replication_controller.go
  pkg/controller/repository/repository_controller.go
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
Labels: enhancement

#8 add godoc, renovate README
  README.md
  pkg/apis/registries/v1alpha1/registry_spec.go
  pkg/apis/registries/v1alpha1/replication_types.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instancechartrepo/instancechartrepo_controller.go
  pkg/controller/internal/harbor_commons.go
  pkg/controller/registry/registry_controller.go
  pkg/controller/replication/replication_controller.go
  pkg/controller/repository/repository_controller.go
  pkg/controller/user/user_controller.go
Labels: documentation

#12 ReplicationSpec: src-/dest-registry -> LocalObjectReference
  deploy/helm-chart/harbor-operator/crds/registries.mittwald.de_replications_crd.yaml
  examples/README.md
  examples/replication_dst.yaml
  examples/replication_src.yaml
  pkg/apis/registries/v1alpha1/replication_types.go
  pkg/apis/registries/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/replication/replication_controller.go
  pkg/controller/replication/replication_controller_test.go
Labels: enhancement

#17 Fix: use correct custom-resource names
  deploy/helm-chart/harbor-operator/templates/instance/user.yaml
  pkg/controller/repository/repository_controller.go
  pkg/controller/user/user_controller.go
Labels: bug

#16 Add code generation to Github workflow
  .github/workflows/workflow.yml
Labels: enhancement

#26 fix instance controller bug, add unit tests
  .github/workflows/godoc.yml
  go.mod
  go.sum
  pkg/apis/registries/v1alpha1/member_role.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
  pkg/internal/helper/hash.go
Labels: bug, enhancement

#28 fix controller handling for termination and setting ids
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
  pkg/controller/registry/registry_controller.go
  pkg/controller/replication/replication_controller.go
  pkg/controller/repository/repository_controller.go
  pkg/controller/user/user_controller.go
Labels: bug

#29 Some fixes for user, replication and repository handling
  deploy/helm-chart/harbor-operator/crds/registries.mittwald.de_replications_crd.yaml
  deploy/helm-chart/harbor-operator/crds/registries.mittwald.de_users_crd.yaml
  deploy/helm-chart/harbor-operator/templates/instance/replication.yaml
  deploy/helm-chart/harbor-operator/templates/instance/user.yaml
  examples/README.md
  examples/replication_dst.yaml
  examples/replication_src.yaml
  examples/user_secret.yaml
  go.mod
  go.sum
  pkg/apis/registries/v1alpha1/replication_types.go
  pkg/apis/registries/v1alpha1/user_types.go
  pkg/controller/instance/instance_controller.go
  pkg/controller/instance/instance_controller_test.go
  pkg/controller/registry/registry_controller.go
  pkg/controller/replication/replication_controller.go
  pkg/controller/repository/repository_controller.go
  pkg/controller/user/secret.go
  pkg/controller/user/user_controller.go
Labels: bug, enhancement

#30 fix replication src- and destRegistry in helm-chart
  deploy/helm-chart/harbor-operator/templates/instance/replication.yaml
Labels: bug
